export const USER_ROOTURL="https://qpz0rsmm2c.execute-api.us-west-2.amazonaws.com/prod/"
export const LIKECOMMENT_ROOTURL="http://localhost:8004"
export const BLOCKCHAIN_ROOTURL=""
export const PAYMENT_ROOTURL=""
export const IMAGE_ROOTURL="http://localhost:8002"
export const IMAGE_CMDURL="http://localhost:8001"