export const USER_ROOTURL="localhost:8080/users"
export const LIKECOMMENT_ROOTURL=""
export const BLOCKCHAIN_ROOTURL=""
export const PAYMENT_ROOTURL=""
export const IMAGE_ROOTURL="http://localhost:8002"
export const IMAGE_CMDURL="http://localhost:8001"